working-groups:
  organizations:
      - quarkusio
      - quarkiverse
  project-prefix: WG -


quarkus:
  smallrye-graphql-client:
    github:
      url: https://api.github.com/graphql
      header:
        Authorization: Bearer ${GITHUB_TOKEN}