name: Build Landing Page

env:
  JVM_VERSION: '21'

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    name: "Generate landing page"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin

      - name: jbang
        uses: jbangdev/jbang-action@v0.116.0
        with:
          script: src/main.java
        env:
          JBANG_REPO: /root/.jbang/repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
