name: Build Landing Page

env:
  JVM_VERSION: '21'

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    name: "Generate landing page"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin
          cache: maven
      - name: Install JBang
        run: curl -Ls https://sh.jbang.dev | bash -s - app setup

      - name: Generate
        run: jbang src/main.java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
